### PR TITLE
Export CMake target

### PR DESCRIPTION
**Pull request by magestik**
I updated the minimum CMake version to 3.1 (aka "modern CMake") in order to export the OpenHMD target with the correct (transitive) dependencies. I did some other minor changes like changing the case of some function calls (everything is lower-case now).

### CODE REVIEW

**Comment by TheOnlyJoey** [comment]
So giving my 2 cents on this.
I personally enjoy building shared and static at the same time, since I use them both a the same time, and my pipeline works well with what we have now.
If others prefer the new method please let me know, I will merge on their behalf then :)

**Comment by magestik** [comment]
Thank you for your feedback.

Maybe I can add an option to allow building both libs ? Something like BUILD_BOTH_STATIC_SHARED_LIBS (named after the default BUILD_SHARED_LIBS variable)

**Comment by TheOnlyJoey** [comment]
Sounds great, I can work with that!

**Comment by magestik** [comment]
Done. I can probably clean it a bit to remove redundant code.

**Comment by magestik** [comment]
I fixed some issues when compiling with MSVC (not related to previous changes). Seems all good now.

**Comment by TheOnlyJoey** [comment]
Normally would rather have them in a separate PR but since these are all CMake optimizations, works for me.

**Pull request merged**
