### PR TITLE
Use PROJECT_SOURCE_DIR for CMAKE_MODULE_PATH

### PR DESCRIPTION
**Pull request by StefanRommel**
The error that occurs using CMAKE_SOURCE_DIR for CMAKE_MODULE_PATH is, that the HIDAPI  package could not be found due to the missing config file FindHIDAPI.cmake. So it is not possible to use OpenHMD in other CMake projects. Using  PROJECT_SOURCE_DIR instead of CMAKE_SOURCE_DIR solves the issue.

For more details see the CMake documentation:
CMAKE_SOURCE_DIR is the path to the top level of the source tree (https://cmake.org/cmake/help/v3.1/variable/CMAKE_SOURCE_DIR.html). It differs, if OpenHMD is included to other projects.
PROJECT_SOURCE_DIR is the top level source directory for the current project. This is the source directory of the most recent project() command. (https://cmake.org/cmake/help/v3.1/variable/PROJECT_SOURCE_DIR.html). Due to the project is defined in the top level CMakeLists.txt the correct path will be used to find the modules.

### CODE REVIEW

**Comment by StefanRommel** [comment]
@ChristophHaag: Can you review it?

**Comment by ChristophHaag** [comment]
Sounds good to me. I don't think this will break anything, or can anyone else think of something?

**Comment by TheOnlyJoey** [comment]
Hmm interesting, never had issues with using OpenHMD in other CMake projects like this. I want to look into this a bit before merging to check some build setups and see what makes the most sense.

**Comment by Stefan0784** [comment]
@TheOnlyJoey did you check build setups if merge is possible?

**Comment by StefanRommel** [comment]
@ChristophHaag @TheOnlyJoey: Some progress? Did you need further informations?

**Comment by TheOnlyJoey** [comment]
Please don't spam the issue tracker with questions about updates, things are done when they are done ;)

**Pull request merged**
