### PR TITLE
build: Remove Autotools build.

### PR DESCRIPTION
**Pull request by lubosz**
This removes autotools, as discussed in the BoF. Not sure when this is going to be merged, but the "work" is done ;)

### CODE REVIEW

**Comment by TheOnlyJoey** [comment]
Pulling this after 0.3 release

**Comment by alexandre-janniaux** [comment]
Please merge #190 or a variant before merging this one, as it prevents from using openhmd in a classic contrib system (so static build) like previously.

**Comment by Wallbraker** [comment]
I have merged #190 as it installed the pkgconfig file even when it was building static.

**Comment by TheOnlyJoey** [comment]
Please update this for merge

**Comment by pH5** [comment]
Updated in #247.

**Pull request closed without merging**
