### PR TITLE
Openglexample modernized

### PR DESCRIPTION
**Pull request by jsarrett**
this updates the opengl example with a bunch of useful stuff.

- it sets the window based on the HMD reported resolution
- it uses the universal shader
- it adds crosshairs which you can use to estimate lens_sep on cv1 style adjustable IPD displays
- it allows disabling lens distortion
- it allows adjusting the distortion scale, in case of calibration FoV mismatches

### CODE REVIEW

**Comment by noname22** [comment]
Looks good. Gotta test it though. We also have another PR with SDL2 etc. Perhaps we should merge these changes with that PR?

**Comment by jsarrett** [comment]
Updated to also build with SDL2, and GLEW.

**Comment by Wallbraker** [comment]
Hey, don't take this a strict no. But I wonder if it would be possible to use gald http://glad.dav1d.de/ instead? Its a generate your own bindings project, it makes it so we can limit the amount of functions that we need to import/parse and so on.

Again you can go ahead and commit as is and switch to glad further down the line or not at all.

**Comment by TheOnlyJoey** [comment]
Since this is fully functional, I will pull this to master.
I am all for exploring Gald as alternative, but rather have that as a additional pull request.

**Pull request merged**
