### PR TITLE
Add support for VIVE Pro

### PR DESCRIPTION
**Pull request by lubosz**
This series of patches adds support for the VIVE Pro. It introduces a revisions enum in the VIVE driver and some magic to turn the display on and off again.
In contrast to the VIVE 1 it apparently also requires a message that enables the IMU.
The config is not implemented yet in this series, so I am initializing the config values with default ones from VIVE 1 which work ok. This is also quite handy if the config fails to be read for any other reason.

Since both VIVEs need different messages to turn off the display I needed to extend the device close method in all drivers to receive the `ohmd_device_desc` as open does.

I also removed a bunch of debug code from the JSON parser, which I should have done last time i touched that code.

I would really appreciate if the commits do not get squashed into one, as I took some extra time to seperate them by concern.

Have a lot of fun.

### CODE REVIEW

**Comment by Wallbraker** [comment]
Looks good to me!

**Comment by TheOnlyJoey** [comment]
> I don't understand why we need to change the driver interface. Can't we just save the device description in the priv structure when opening the device?

Well it might be a case that multiple devices need to use in the future as well, and we do have this information on Open, so it makes sense having it on close?

**Comment by lubosz** [comment]
> I don't understand why we need to change the driver interface. Can't we just save the device description in the priv structure when opening the device?

I could have copied the description struct to the priv one, but it seemed rather than a hack to me to duplicate this data and it might make sense for other devices with multiple revisions.

**Comment by noname22** [comment]
First off, thanks for the hard work put into the patch. It's very appreciated.

I do, however, take issue with giving close() the device descriptor again for the reasons listed below:

### Solve the problem at hand

In my opinion, a patch should solve the probelm at hand with as little effort, code and changes as possible. We shouldn't be concerened with solving some hypothetical future problem. We have enough to solve as it is without having to invent new ones. If, indeed, the other drivers would have to know what device they're opening we'll deal with that problem then.

### Separation of concerns

It might not be immediately apparent, but OpenHMD is an object oriented project. As such, each object should handle its own concerns. If an object needs to remember a parameter it was given in the constructor, it is its own responsibility to do so and not the caller's.

For instance, ifstream in C++ doesn't take the path of the file you just opened in its close() method, whether that "saves memory" or not. (Neither does fclose() for that matter).

Imagine for a second that OpenHMD was written in C++. The device class would look something like:

```
class Device 
{
	public:
	virtual int Getf(ohmd_float_value type, float* out) = 0;
	//...

	virtual void Update() = 0;
	virtual void Close() = 0;
};

class ViveDevice : public Device
{
	public:
	ViveDevice(const DeviceDesc* desc)
	{
		// ...
	}

	void Update() { /* ... */ }
	void Close()
	{
	}
};
```

Do you still think Close should get the device descriptor as input? Because it's architecturally literally the exact same thing, only in a different language.

Suggested solution:

Put a vive_revision field in vive_priv. It's the only field in desc we're interested in keeping and might very well be for the forseeable future. No need to change all the drivers for no immediate benefit.

Do you guys agree or no?

**Comment by lubosz** [comment]
Updated the branch. It now stores the revision in the `priv` struct.

I also added a correct display resolution. The other config values are properly not correct for the pro and should be aquired from the HMD config where possible.
I also fixed the IMU orientation which was wrong on the first version of the PR.
Tested it in xrgears and the openglexample. Works for me on both devices.

**Pull request merged**
