### PR TITLE
add meson build

### PR DESCRIPTION
**Pull request by ChristophHaag**
I'm sure it can be improved but as is, it works.

Example usage:

    meson -DOPENHMD_EXAMPLE_SDL=true --prefix=$PWD/install --libdir=lib -Dbuildtype=release build
    ninja -C build install

### CODE REVIEW

**Comment by ChristophHaag** [comment]
The current variable names and config options are taken 1:1 from the cmake build script. I thought it would be nice to have the same options in both build systems.

But sure, it would be no problem for me to change it.

**Comment by ChristophHaag** [comment]
New example invocation:

    meson -Dexamples=simple,opengl -Ddrivers=oculus,deepoon,psvr,vive,nolo,external --prefix=$PWD/install --libdir=lib -Dbuildtype=release build

As with the autotools and cmake build, that's actually the default value for enabled drivers so `-Ddrivers` doesn't need to specified when you want everything but android.

**Comment by pH5** [comment]
Thanks, it is getting close. The shared_library invocation is missing a version parameter (currently '0.0.0'), and there is no static_library. I'd like the 'oculus' option to be renamed to 'rift' (like 'vive' is not 'htc').

**Comment by ChristophHaag** [comment]
I haven't really found docs about how to make meson add a static library to the pkg-config file. Maybe installing a second pkg-config file with a different name?

Currently it looks like this to build a shared library:

    meson --default-library=shared -Ddrivers=rift,deepoon,psvr,vive,nolo,external --prefix=$PWD/install --libdir=lib -Dbuildtype=release build

--default-library=shared is the default and can be omitted.

    meson --default-library=static -Ddrivers=rift,deepoon,psvr,vive,nolo,external --prefix=$PWD/install --libdir=lib -Dbuildtype=release build

will build and install only the static library and ignores the examples, the pkg-config file and the header for now.

I'm not too happy with this, but it probably does what most people want, if they want to link a static library...

**Pull request merged**
